#!/bin/bash
#
# DESCRIPTION:
#
#   Set the screen brightness with the "Light" program.
#
# DEPENDENCIES:
#
#   Light (https://github.com/haikarainen/light)
#
# Author: clyde80
# Website: https://github.com/clyde80/i3-configuration
# Created on: November 24, 2016
# Updated on: February 22, 2017
#
# To file a bug report, create an issue on GitHub:
# https://github.com/clyde80/i3-configuration/issues
#
# To submit a bug fix, create a pull request on the working branch:
# https://github.com/clyde80/i3-configuration/tree/working

readonly USAGE="Usage: $(basename $0) [-ud] <value> -- Sets the screen brightness

OPTIONS

    -u      --up    Raise the screen brightness by <value>
    -d      --down  Lower the screen brightness by <value>

    -h      --help  Display this help message

EXAMPLES
    
    Increase screen brightness by 5:
        $(basename $0) -u 5

    Decrease screen brightness by 5:
        $(basename $0) -d 5
 
Author: clyde80
Website: https://github.com/clyde80/i3-configuration
Created on: November 24, 2016
Updated on: February 22, 2017

To file a bug report, create an issue on GitHub:
https://github.com/clyde80/i3-configuration/issues

To submit a bug fix, create a pull request on the working branch:
https://github.com/clyde80/i3-configuration/tree/working"

# Parse the command arguments.
case $1 in
    "-u"|"--up") light -A $2 ;;
    "-d"|"--down") light -U $2 ;;
    "-h"|"--help")
        echo "$USAGE"
        exit 0
        ;;
    *) 
        echo "Unknown option: $1"
        exit 1 
        ;;
esac

notify-send -t 675 "Brightness: $(light)"
