#!/bin/bash
#
# Sets the screen brightness using the "light" program.
# 
# Depends on:
# Light (https://github.com/haikarainen/light)
# 
# Author: clyde80
# Website: https://github.com/clyde80
# Created on: November 24, 2016
# Updated on: December 22, 2016
#
print_help() {
    echo "Sets the screen brightness"
    echo "Usage: backlight -[ud] <value>"
    echo
    echo "-u    --up    Raises the screen brightness by <value>"
    echo "-d    --down  Lowers the screen brightness by <value>"
    echo
    echo "Type 'backlight -h' to display this help message"
    echo
    echo "Author: clyde80"
    echo "Website: https://github.com/clyde80"
    echo "Created on: November 24, 2016"
    echo "Updated on: December 22, 2016"
    echo
    echo "Depends on 'light'"
    echo "https://github.com/haikarainen/light"
}

# Parse the command arguments.
case $1 in
    "-u"|"--up")
        light -A $2;;
    "-d"|"--down")
        light -U $2;;
    "-h"|"--help")
        print_help
        exit 0;;
    *)
        exit 1;;
esac

notify-send -t 675 "Brightness: $(light)"
