#!/bin/bash
#
# Prints the connected wifi network using NetworkManager CLI (nmcli)
#
# DEPENDENCIES:
#   NetworkManager
#
# Usage:
#   getwifinetwork
#
# Author: clyde80
# Website: https://github.com/clyde80
# Created On: December 22, 2016
# Updated On: February 12, 2017
#
# To file a bug report, create an issue on Github:
# https://github.com/clyde80/i3-configuration/issues
#
# To submit a bug fix, create a pull request on the working branch:
# https://github.com/clyde80/i3-configuration/tree/working

output=$(nmcli -t -f active,ssid dev wifi | grep "yes")
if [[ ! -z "$output" ]]; then
    echo "WIFI: OK"
else
    echo "WIFI: NOT OK"
fi
