#!/bin/bash
if [ $# -ne 3 ]; then
    echo "Usage: gifenc [input file] [output file] [scale-width]"
    exit 0
fi
palette="/tmp/palette.png"

filters="fps=15,scale=$3:-1:flags=lanczos"

ffmpeg -v warning -i $1 -vf "$filters,palettegen" -y $palette
ffmpeg -v warning -i $1 -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y $2
