#!/bin/bash
#
# A script used to list and remove empty directories.
#
# Author: clyde80
# Website: https://github.com/clyde80/i3-configuration
# Updated on: February 12, 2017
#
# To file a bug report, create an issue on Github:
# https://github.com/clyde80/i3-configuration/issues
#
# To submit a bug fix, create a pull request on the working branch:
# https://github.com/clyde80/i3-configuration/tree/working

usage="Usage: $(basename "$0") [-h] [-l r] directory
A script that removes empty directories

OPTIONS
    -l      --list      List the directories that would be deleted
    -r      --remove    Remove the directories (can't use with -l)

    It is recommended to use --list before using --remove so you know what will
    be removed.

    -h      --help      Display this help message

    Author: clyde80
    Website: https://github.com/clyde80/i3-configuration
    Updated on: February 12, 2017

    To file a bug report, create an issue on Github:
    https://github.com/clyde80/i3-configuration/issues

    To submit a bug fix, create a pull request on the working branch:
    https://github.com/clyde80/i3-configuration/tree/working"

if [[ $# -eq 0 || $# -ne 2 || "$1" -eq "-h" ]]; then
    echo "$usage"
    exit 0
fi

case $1 in
    "-h"|"--help") echo "$usage" ;;
    "-l"|"--list")
        shift
        find $1 -type d -empty -print
        ;;
    "-r"|"--remove")
        shift
        find $1 -type d -empty -delete
        ;;
    *)
        echo "Option $1 not found"
        echo "$usage"
        exit 1
        ;;
esac

exit 0
