#!/bin/bash
#
# DESCRIPTION:
#
#   Print or remove empty directories.
#
# Author: clyde80
# Website: https://github.com/clyde80/i3-configuration
# Updated on: February 22, 2017
#
# To file a bug report, create an issue on Github:
# https://github.com/clyde80/i3-configuration/issues
#
# To submit a bug fix, create a pull request on the working branch:
# https://github.com/clyde80/i3-configuration/tree/working

readonly USAGE="Usage: $(basename "$0") [-h] [-l r] directory

DESCRIPTION

    Print or remove empty directories

OPTIONS

    -p      --print     Print empty directories (can't be used with -p)
    -r      --remove    Remove the directories (can't use with -l)

    It is recommended to use --print before using --remove so you know what will
    be removed.

    -h      --help      Display this help message

Author: clyde80
Website: https://github.com/clyde80/i3-configuration
Updated on: February 22, 2017

To file a bug report, create an issue on Github:
https://github.com/clyde80/i3-configuration/issues

To submit a bug fix, create a pull request on the working branch:
https://github.com/clyde80/i3-configuration/tree/working"

if [[ $# -eq 0 || $# -ne 2 || "$1" -eq "-h" ]]; then
    echo "$USAGE"
    exit 0
fi

case $1 in
    "-h"|"--help") echo "$USAGE" ;;
    "-p"|"--print")
        shift
        find $1 -type d -empty -print
        ;;
    "-r"|"--remove")
        shift
        find $1 -type d -empty -delete
        ;;
    *)
        echo "Option $1 not found"
        echo "$USAGE"
        exit 1
        ;;
esac

exit 0
