#!/bin/bash
# 
# Sets the audio output device to headphones, speaker, or HDMI using 
# PulseAudio.
#
# Author: clyde80
# Website: https://github.com/clyde80
# Created on: November 30, 2016
# Updated on: December 22, 2016
#
print_help(){
    echo "Sets the audio output device to headphones, speakers, or HDMI."
    echo "Usage: sao -[esdt]"
    echo 
    echo "-e    --headphones    Sets the audio output to headphones"
    echo "-s    --speaker       Sets the audio output to speakers"
    echo "-d    --hdmi          Sets the audio output to HDMI"
    echo "-t    --toggle        Toggle between headphones and speakers"
    echo
    echo "Type 'sao -h' to display this help message"
    echo
    echo "Author: clyde80"
    echo "Website: https://github.com/clyde80"
    echo "Created on: November 30, 2016"
    echo "Updated on: December 22, 2016"
}

# Set the audio output device to headphones.
set_output_to_headphones() {
    pactl set-card-profile 0 output:analog-stereo
    pacmd set-sink-port "$(pacmd list-sinks | grep index | grep -o '[0-9]*')" analog-output-headphones
    exit 0
}

# Set the audio output device to speakers.
set_output_to_speakers() {
    pactl set-card-profile 0 output:analog-stereo
    pacmd set-sink-port "$(pacmd list-sinks | grep index | grep -o '[0-9]*')" analog-output-speaker
    exit 0
}

# Set the audio output device to HDMI.
set_output_to_hdmi() {
    pactl set-card-profile 0 output:hdmi-stereo
    exit 0
}

# Parse the command line arguments.
case $1 in
    "-h"|"--help") print_help; exit 0;;
    "-e"|"--headphones") set_output_to_headphones;;
    "-s"|"--speaker") set_output_to_speakers;;
    "-d"|"--hdmi") set_output_to_hdmi;;
    "-t"|"--toggle")
        # Get whether or not the headphones are being used.
        output=$(pacmd list-sinks | grep "active port")
        headphones=false
        case $output in
                *"<analog-output-headphones>"*) headphones=true;;
        esac

        # Toggle between headphones and speakers.
        if [ "$headphones" = true ]; then
            set_output_to_speakers
        else
            set_output_to_headphones
        fi;;
    *)
        echo "Command $1 not found"
        print_help
        exit 1;;
esac
