#!/bin/bash
#
# DESCRIPTION:
#
#   Set a dual monitor display (HDMI and main display).
#
# DEPENDENCIES:
#
#   xorg-xrandr, feh
#
# Author: clyde80
# Website: https://github.com/clyde80
# Created on: November 30, 2016
# Updated on: February 23, 2017
#
# To file a bug report, create an issue on GitHub:
# https://github.com/clyde80/i3-configuration/issues
#
# To submit a bug fix, create a pull request on the working branch:
# https://github.com/clyde80/i3-configuration/tree/working

readonly USAGE="Usage: $(basename "$0") [-s r]

DESCRIPTION

    Set a dual monitor display (HDMI and main display)

OPTIONS

    -s      --set       Set the dual monitor display
    -r      --reset     Resets the dual monitor display to a single monitor display

    -h      --help      Display this help method

Author: clyde80
Website: https://github.com/clyde80/i3-configuration
Created on: November 30, 2016
Updated on: February 23, 2017

To file a bug report, create an issue on GitHub:
https://github.com/clyde80/i3-configuration/issues

To submit a bug fix, create a pull request on the working branch:
https://github.com/clyde80/i3-configuration/tree/working"

case $1 in
    "-h"|"--help")
        echo "$USAGE"
        exit 0
        ;;
    "-s"|"--set")

        # Set the multi monitor display. HDMI-1 is the name of the second 
        # monitor to use. You can find the name of your monitor by typing 
        # "xrandr" into your terminal. The monitor name is to the left of the
        # status (connected|disconnected). 
        #
        # If you want the second monitor to be to the right of the primary 
        # monitor, you can replace "--left-of" with "--right-of".
        #
        # Replace "--left-of" with "--same-as" to mirror primary display to 
        # second display.
        xrandr --output HDMI-1 --auto --right-of LVDS-1

        # Set the background image again because the background image is messed
        # up when adding another screen.
        feh --bg-fill /home/cat/Pictures/wallpapers/current/current.png

        # Set the audio output to HDMI
        sao -d
        exit 0
        ;;
    "-r"|"--reset")

        # Set the main display to LVDS-1. Again, you can find names of the 
        # different displays by typing "xrandr" into your terminal. 
        xrandr --output LVDS-1 --mode 1366x768 --primary

        # Stop using HDMI-1.
        xrandr --output HDMI-1 --off

        # Set the background image again because the background image is 
        # messed up when turning off the screen.
        feh --bg-scale /home/cat/Pictures/wallpapers/current/current.png

        # Set the audio output to speaker.
        sao -s
        exit 0
        ;;
    *)
        echo "Option $1 not found"
        echo "$USAGE"
        exit 1
        ;;
esac
