#!/bin/bash
#
# This script will change the volume of the system and will also provide audio
# feedback (optional) and display a notification with the system volume. This 
# script uses amixer.
#
# Author: clyde80
# Website: https://github.com/clyde80
# Created on: November 22, 2016
# Updated on: December 22, 2016
#
print_help() {
    echo "Usage: vol -[rlm] -b [value]"
    echo
    echo "-r    --raise     Raises the volume by 5"
    echo "-l    --lower     Lowers the volume by 5"
    echo "-m    --mute      Toggles mute"
    echo
    echo "-b    --beep      Whether or not to beep on sound change"
    echo "                  Specify a value of 1 or 2 for a different beep"
    echo "                  sound"
    echo
    echo "Type 'vol -h' to display this help message"
    echo
    echo "Author: clyde80"
    echo "Website: https://github.com/clyde80"
    echo "Created on: November 22, 2016"
    echo "Updated on: December 22, 2016"
}

if [ $# -eq 0 ]; then
    print_help
    exit 0
fi

# Determine if the sound can be changed.
can_change=false
if [ -z "$(amixer get Master | grep off)" ]; then
    can_change=true
fi

# Parse the command arguments.
case $1 in
    "-r"|"--raise")
        if [ "$can_change" = true ]; then
            amixer set Master 5%+ # Increase volume by 5
        fi;;
    "-l"|"--lower")
        if [ "$can_change" = true ]; then
            amixer set Master 5%- # Decrease volume by 5
        fi;;
    "-m"|"--mute") 
        amixer set Master toggle # Mute/Unmute

        # Determine if sound is muted or not and provide a notification.
        if [ "$can_change" = false ]; then
            notify-send -t 675 "Sound unmuted"
            case $2 in 
                "-b"|"--beep") 
                    if [ $3 -eq 1 ]; then
                        aplay /usr/share/sounds/freedesktop/stereo/beep1.wav
                    elif [ $3 -eq 2 ]; then
                        aplay /usr/share/sounds/freedesktop/stereo/beep2.wav
                    else    
                        echo "No sound for -b $3 found."
                    fi;;
                *)
                    echo "Invalid argument: $2"
                    exit 1;;
            esac
        else
            notify-send -t 675 "Sound muted"
        fi
        exit 0;;
    "-h"|"--help")
        print_help
        exit 0;;
    *)
        echo "Invalid option: $1"
        exit 1;;
esac

# Display a notification to the user using notify-send command.
notify-send -t 675 "$(getvolume)"

case $2 in
    "-b"|"--beep")
        if [ $3 -eq 1 ]; then
            aplay /usr/share/sounds/freedesktop/stereo/beep1.wav
        elif [ $3 -eq 2 ]; then
            aplay /usr/share/sounds/freedesktop/stereo/beep2.wav
        else
            echo "No sound for -b $3 found."
        fi;;
    *)
        echo "Invalid argument: $2"
        exit 1;;
esac

exit 0
