#!/bin/bash

print_help() {
    echo "Usage: vol [-rlm] -b"
    echo
    echo "-r    --raise     Raises the volume by 5"
    echo "-l    --lower     Lowers the volume by 5"
    echo "-m    --mute      Toggles mute"
    echo
    echo "-b    --beep      Whether or not to beep on sound change"
    echo
    echo "Type sah -h to display this help message"
    echo
    echo "--------------------------------------------"
    echo "Author: clyde80"
    echo "Website: https://github.com/clyde80"
    echo "Date: November 22, 2016"
}

# Determine if the sound can be changed.
can_change=false
if [ -z "$(amixer get Master | grep off)" ]; then
    can_change=true
fi
echo $can_change

case $1 in
    "-r"|"--raise")
        if [ "$can_change" = "true" ]; then
            amixer set Master 5%+
        fi;;
    "-l"|"--lower")
        if [ "$can_change" = "true" ]; then
            amixer set Master 5%-
        fi;;
    "-m"|"--mute") 
        amixer set Master toggle

        # Determine if sound is muted or not and provide a notification.
        if [ "$can_change" == "false" ]; then
            notify-send -t 2 "Sound unmuted"
            case $2 in 
                "-b"|"--beep") aplay /usr/share/sounds/beep.wav
            esac
        else
            notify-send -t 2 "Sound muted"
        fi
        exit 0;;
    "-h"|"--help")
        print_help
        exit 0;;
    *)
        exit 1;;
esac

# Display a notification to the user using notify-send command.
notify-send -t 2 "Volume $(amixer get Master |grep % | head -n 1 |awk '{print $5}'|sed 's/[^0-9\%]//g')"

case $2 in
    "-b"|"--beep")
        aplay /usr/share/sounds/beep.wav;;
    *)
        exit 1;;
esac

exit 0
